%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
# https://carnegierobotics.com/support-updates/
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
# camera matrix
# data: [(Camera.fx), 0, (Camera.cx), 0, (Camera.fy), (Camera.cy), 0, 0, 1 ]
Camera.fx: 811.985107
Camera.fy: 815.353232
Camera.cx: 345.840528
Camera.cy: 181.497735

# distortion_coefficients
# data: [(Camera.k1), (Camera.k2), (Camera.p1), (Camera.p2), (Camera.k3)]
Camera.k1: 0.262218
Camera.k2: -1.050505
Camera.p1: 0.024262
Camera.p2: -0.030305

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30.0

# stereo baseline times fx
# is the horizontal focal length (in pixels) multiplied by the baseline (in meters). (Camera.fx * baseline)
Camera.bf: 52.88849601 # (((Camera.fx + Camera.fy) / 2) * baseline)

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
# ThDepth can be safely set around 50.
ThDepth: 30

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 640
LEFT.width: 480
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.262218, -1.050505, 0.024262, -0.030305, 0.000000]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [811.985107, 0.000000, 345.840528, 0.000000, 815.353232, 181.497735, 0.000000, 0.000000, 1.000000]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.966787, 0.024909, 0.254367, -0.024770, 0.999686, -0.003752, -0.254380, -0.002674, 0.967101]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [961.738575, 0.000000, 114.379494, 0.000000, 0.000000, 961.738575, 194.362007, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]

RIGHT.height: 640
RIGHT.width: 480
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.073677, 0.473848, 0.014554, -0.031155, 0.000000]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [856.117179, 0.000000, 322.864369, 0.000000, 847.463144, 190.242413, 0.000000, 0.000000, 1.000000]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.984327, 0.019540, 0.175266, -0.019636, 0.999806, -0.001189, -0.175255, -0.002271, 0.984520]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [961.738575, 0.000000, 114.379494, 691.797960, 0.000000, 961.738575, 194.362007, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid   
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid  
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast     
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.5
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize: 1
Viewer.CameraSize: 0.5
Viewer.CameraLineWidth: 1
Viewer.ViewpointX: 0.00001
Viewer.ViewpointY: 0.00001
Viewer.ViewpointZ: 0.00001
Viewer.ViewpointF: 2000